version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/data.db:/usr/src/app/data.db

  simulator:
    build:
      context: ./simulator
    command: ["node", "simulator.js"]
    environment:
      - SERVER_URL=http://server:3000
    depends_on:
      - server
